name: Docker-ACES-test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:

  build-aces-1_0_1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --rm -f Dockerfile_ACES_1_0_1_test -t ctl:latest .

    - name: Run the Docker image
      run: docker run ctl:latest

  build-aces-1_3:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --rm -f Dockerfile_ACES_1_3_test -t ctl:latest .

    - name: Run the Docker image
      run: docker run ctl:latest
